name: Featured Entry
id: FeaturedEntry
author_link: http://appnel.com/
author_name: The Appnel Group
description: Enables "sticky" featured entries.
version: 0.2
schema_version: 0.2
object_types:
    entry:
        is_featured: smallint
callbacks:
    MT::App::CMS::template_param.edit_entry: $FeaturedEntry::MT::FeaturedEntry::Sticky::add_sticky_checkbox
    MT::App::CMS::cms_pre_save.entry: $FeaturedEntry::MT::FeaturedEntry::Sticky::save_featured_status
tags:
    block:
        BlogStickyEntry: $FeaturedEntry::MT::FeaturedEntry::Sticky::blog_sticky_entry
        BlogIfHasSticky?: $FeaturedEntry::MT::FeaturedEntry::Sticky::if_blog_has_sticky
        EntryIsSticky?: $FeaturedEntry::MT::FeaturedEntry::Sticky::if_entry_is_sticky
